version: "3.5"
services:
  plc:     
    image: aut/vip:${CONTAINER_VERSION}
    env_file:
      - .env.test
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip install -e . && bash"
    tty: true
    restart: always
    container_name: plc_tester
    networks:
      - vip_net
    logging:
        driver: "json-file"
        options:
            max-file: ${LOG_FILES}
            max-size: ${LOG_SIZE}
networks:
  default:
    name: vip_net
    external: true  